services:
  backend:
    build:
      context: /mounts/financebud
      dockerfile_inline: |
        FROM python:3.11-slim
        WORKDIR /app
        COPY requirements.txt .
        RUN pip install --no-cache-dir -r requirements.txt
    env_file:
      - stack.env
    environment:
      - DATABASE_PATH=/app/financial_data.db
      - STATEMENTS_DIR=/app/Bank-Statements
      - APP_HOME=/app
    command: sh -c "python3 consolidate_statements.py && python -m uvicorn backend.main:app --host 0.0.0.0 --port 8000"
    volumes:
      - /home/notroot/Work/podlab/data/mounts/financebud/:/app